from fastapi import FastAPI, File, UploadFile, Request, Response
from fastapi.responses import StreamingResponse, HTMLResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.templating import Jinja2Templates
from openai import OpenAI
import io
import PyPDF2
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
import textwrap
from concurrent.futures import ThreadPoolExecutor
from dotenv import load_dotenv
import os
from reportlab.pdfbase.pdfmetrics import stringWidth
import secrets
import asyncio

# Load OpenAI key
load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

app = FastAPI()

# ----- CORS if needed -----
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ----- Templates folder -----
templates = Jinja2Templates(directory="templates")

# ----- Rate limiting storage (cookie-based) -----
user_requests = {}  # user_id -> count
MAX_REQUESTS_PER_DAY = 3

# ----- Helpers -----
def pdf_to_text(file: UploadFile):
    reader = PyPDF2.PdfReader(file.file)
    text = ""
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"
    return text

def chunk_text(text, max_tokens=4000):
    chunk_size = max_tokens * 4  # approx 1 token ~ 4 chars
    return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]

def create_summary_pdf(summary: str):
    pdf_buffer = io.BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=LETTER)
    width, height = LETTER
    x = inch
    y = height - inch
    line_height = 14
    footer_text = "Generated by PSA"
    page_number = 1

    def draw_footer(page_num):
        text = f"{footer_text} | Page {page_num}"
        text_width = stringWidth(text, "Helvetica", 10)
        c.setFont("Helvetica", 10)
        c.drawString((width - text_width) / 2, 0.5 * inch, text)

    for line in summary.split("\n"):
        wrapped_lines = textwrap.wrap(line, width=90)
        for segment in wrapped_lines:
            if y < inch:
                draw_footer(page_number)
                c.showPage()
                page_number += 1
                y = height - inch
            c.drawString(x, y, segment)
            y -= line_height

    draw_footer(page_number)
    c.save()
    pdf_buffer.seek(0)
    return pdf_buffer

async def summarize_chunk(chunk: str):
    prompt = (
        f"You are a document summarization assistant. You are receiving a portion "
        f"of a larger document, and your task is to identify and extract the key points, "
        f"main ideas, important information, critical data, statistics, findings, "
        f"and conclusions from this section, then create a clear, concise summary that "
        f"captures the essential content using professional language while maintaining "
        f"the original meaning and focusing only on the content in this section, "
        f"outputting only the summary text in paragraph form without any preamble, "
        f"meta-commentary, or explanations. Word limit is 100 words\n{chunk}"
    )
    loop = asyncio.get_running_loop()
    response = await loop.run_in_executor(
        None,
        lambda: client.chat.completions.create(
            model="gpt-5-nano",
            messages=[{"role": "user", "content": prompt}]
        )
    )
    return response.choices[0].message.content

async def summarize_text(text: str):
    chunks = chunk_text(text)
    tasks = [summarize_chunk(c) for c in chunks]
    summaries = await asyncio.gather(*tasks)
    return "\n\n".join(summaries)

# ----- Routes -----
@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

@app.post("/")
async def upload(document: UploadFile = File(...), request: Request = None):
    # Cookie-based rate limiting
    user_id = request.cookies.get("user_id") or secrets.token_hex(8)
    count = user_requests.get(user_id, 0)
    if count >= MAX_REQUESTS_PER_DAY:
        return Response("Rate limit exceeded", status_code=429)
    user_requests[user_id] = count + 1

    # Process PDF
    text = pdf_to_text(document)
    summary = await summarize_text(text)
    pdf_file = create_summary_pdf(summary)

    response = StreamingResponse(pdf_file, media_type="octet-stream")
    response.headers["Content-Disposition"] = "attachment; filename=summary.pdf"
    if not request.cookies.get("user_id"):
        response.set_cookie("user_id", user_id)
    return response

