from fastapi import FastAPI, File, UploadFile, Request, Response, BackgroundTasks, HTTPException
from fastapi.responses import StreamingResponse, HTMLResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.templating import Jinja2Templates
from openai import OpenAI
import io
import PyPDF2
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
import textwrap
from dotenv import load_dotenv
import os
from reportlab.pdfbase.pdfmetrics import stringWidth
import secrets
import asyncio
import uuid
import time

# Load OpenAI key
load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

app = FastAPI()

# ----- CORS if needed -----
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ----- Templates folder -----
templates = Jinja2Templates(directory="templates")

# ----- Rate limiting storage (cookie-based) -----
user_requests = {}  # user_id -> count
MAX_REQUESTS_PER_DAY = 3

# ----- In-memory job store for progress polling -----
# job_id -> { "stage": str, "message": str, "pdf_bytes": bytes|None, "created_at": float }
# Stages: "uploading" -> "extracting" -> "summarizing" -> "done"  (or "error")
jobs = {}

JOB_TTL_SECONDS = 30 * 60  # cleanup jobs older than 30 minutes


def cleanup_old_jobs():
    cutoff = time.time() - JOB_TTL_SECONDS
    stale_ids = [jid for jid, job in jobs.items() if job["created_at"] < cutoff]
    for jid in stale_ids:
        jobs.pop(jid, None)


# ----- Helpers -----
def pdf_to_text(file_bytes: bytes):
    reader = PyPDF2.PdfReader(io.BytesIO(file_bytes))
    text = ""
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"
    return text

def chunk_text(text, max_tokens=4000):
    chunk_size = max_tokens * 4  # approx 1 token ~ 4 chars
    return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]

def create_summary_pdf(summary: str):
    pdf_buffer = io.BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=LETTER)
    width, height = LETTER
    x = inch
    y = height - inch
    line_height = 14
    footer_text = "Generated by PSA"
    page_number = 1

    def draw_footer(page_num):
        text = f"{footer_text} | Page {page_num}"
        text_width = stringWidth(text, "Helvetica", 10)
        c.setFont("Helvetica", 10)
        c.drawString((width - text_width) / 2, 0.5 * inch, text)

    for line in summary.split("\n"):
        wrapped_lines = textwrap.wrap(line, width=90)
        for segment in wrapped_lines:
            if y < inch:
                draw_footer(page_number)
                c.showPage()
                page_number += 1
                y = height - inch
            c.drawString(x, y, segment)
            y -= line_height

    draw_footer(page_number)
    c.save()
    pdf_buffer.seek(0)
    return pdf_buffer

async def summarize_chunk(chunk: str):
    prompt = (
        f"You are a document summarization assistant. You are receiving a portion "
        f"of a larger document, and your task is to identify and extract the key points, "
        f"main ideas, important information, critical data, statistics, findings, "
        f"and conclusions from this section, then create a clear, concise summary that "
        f"captures the essential content using professional language while maintaining "
        f"the original meaning and focusing only on the content in this section, "
        f"outputting only the summary text in paragraph form without any preamble, "
        f"meta-commentary, or explanations. Word limit is 100 words\n{chunk}"
    )
    loop = asyncio.get_running_loop()
    response = await loop.run_in_executor(
        None,
        lambda: client.chat.completions.create(
            model="gpt-5-nano",
            messages=[{"role": "user", "content": prompt}]
        )
    )
    return response.choices[0].message.content

async def summarize_text(text: str):
    chunks = chunk_text(text)
    tasks = [summarize_chunk(c) for c in chunks]
    summaries = await asyncio.gather(*tasks)
    return "\n\n".join(summaries)


async def process_job(job_id: str, file_bytes: bytes):
    """Background task: runs the full pipeline, updating job stage as it goes."""
    try:
        jobs[job_id]["stage"] = "extracting"
        text = pdf_to_text(file_bytes)

        if not text.strip():
            jobs[job_id]["stage"] = "error"
            jobs[job_id]["message"] = "Couldn't read any text from that PDF. It may be scanned or image-only."
            return

        # Keep extracted text around so we can re-summarize without re-parsing the PDF.
        jobs[job_id]["text"] = text

        jobs[job_id]["stage"] = "summarizing"
        summary = await summarize_text(text)

        jobs[job_id]["summary_text"] = summary
        pdf_buffer = create_summary_pdf(summary)
        jobs[job_id]["pdf_bytes"] = pdf_buffer.getvalue()
        jobs[job_id]["stage"] = "done"

    except Exception as exc:
        jobs[job_id]["stage"] = "error"
        jobs[job_id]["message"] = "Something went wrong while processing your document."


async def resummarize_job(job_id: str):
    """Background task: re-runs summarization on already-extracted text."""
    job = jobs.get(job_id)
    if not job:
        return
    try:
        text = job.get("text", "")
        if not text.strip():
            job["stage"] = "error"
            job["message"] = "Couldn't read any text from that PDF. It may be scanned or image-only."
            return

        job["stage"] = "summarizing"
        summary = await summarize_text(text)

        job["summary_text"] = summary
        pdf_buffer = create_summary_pdf(summary)
        job["pdf_bytes"] = pdf_buffer.getvalue()
        job["stage"] = "done"

    except Exception as exc:
        job["stage"] = "error"
        job["message"] = "Something went wrong while re-summarizing your document."


# ----- Routes -----
@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})


@app.post("/upload")
async def upload(background_tasks: BackgroundTasks, document: UploadFile = File(...), request: Request = None):
    cleanup_old_jobs()

    # Cookie-based rate limiting (unchanged from original)
    user_id = request.cookies.get("user_id") or secrets.token_hex(8)
    count = user_requests.get(user_id, 0)
    if count >= MAX_REQUESTS_PER_DAY:
        raise HTTPException(status_code=429, detail="Rate limit exceeded. Please try again later.")
    user_requests[user_id] = count + 1

    if document.content_type != "application/pdf":
        raise HTTPException(status_code=400, detail="Please upload a PDF file.")

    file_bytes = await document.read()

    job_id = str(uuid.uuid4())
    jobs[job_id] = {
        "stage": "uploading",
        "message": "",
        "text": None,
        "summary_text": None,
        "pdf_bytes": None,
        "created_at": time.time(),
    }

    background_tasks.add_task(process_job, job_id, file_bytes)

    response = JSONResponse({"job_id": job_id})
    if not request.cookies.get("user_id"):
        response.set_cookie("user_id", user_id)
    return response


@app.get("/status/{job_id}")
async def status(job_id: str):
    job = jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found.")
    return {"stage": job["stage"], "message": job.get("message", "")}


@app.get("/preview/{job_id}")
async def preview(job_id: str):
    job = jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found.")
    if job["stage"] != "done" or not job.get("summary_text"):
        raise HTTPException(status_code=409, detail="This summary isn't ready yet.")

    words = job["summary_text"].split()
    preview_word_limit = 300
    preview_text = " ".join(words[:preview_word_limit])
    truncated = len(words) > preview_word_limit

    return {
        "preview": preview_text,
        "truncated": truncated,
        "word_count": len(words),
    }


@app.post("/resummarize/{job_id}")
async def resummarize(job_id: str, background_tasks: BackgroundTasks):
    job = jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found.")
    if job["stage"] not in ("done", "error"):
        raise HTTPException(status_code=409, detail="This job is still processing.")

    job["stage"] = "summarizing"
    job["message"] = ""
    job["summary_text"] = None
    job["pdf_bytes"] = None

    background_tasks.add_task(resummarize_job, job_id)

    return {"job_id": job_id}


@app.post("/reject/{job_id}")
async def reject(job_id: str):
    jobs.pop(job_id, None)
    return {"status": "rejected"}


@app.get("/download/{job_id}")
async def download(job_id: str):
    job = jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found.")
    if job["stage"] != "done" or not job["pdf_bytes"]:
        raise HTTPException(status_code=409, detail="This summary isn't ready yet.")

    pdf_stream = io.BytesIO(job["pdf_bytes"])
    response = StreamingResponse(pdf_stream, media_type="application/pdf")
    response.headers["Content-Disposition"] = "attachment; filename=summary.pdf"
    return response
